<?php
/**
 * ScoreTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Thas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Thieme Meulenhoff Analytics Data API
 *
 * First setup of an API to exchange Learning Analytics. This API is based on events (inspired by Caliper Analytics® Specification, version 1.1) that are send to the api. We use a number of events.  The view event is used to register page views for theory.  The grade event is used to register results of doing assignments. Such a result is modelled as a score.  The assesment event is used to register the completion of an assignment. This information is transfered as an attempt.  Both theory and assignments are considered digital resources. An assignment is an assignable digital resource.  A student is seen as an actor.
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Thas;

use PHPUnit\Framework\TestCase;

/**
 * ScoreTest Class Doc Comment
 *
 * @category    Class
 * @description The score for an attempt to make an assignment
 * @package     Thas
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScoreTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Score"
     */
    public function testScore()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "attempt_id"
     */
    public function testPropertyAttemptId()
    {
    }

    /**
     * Test attribute "max_result_score"
     */
    public function testPropertyMaxResultScore()
    {
    }

    /**
     * Test attribute "result_score"
     */
    public function testPropertyResultScore()
    {
    }
}
