<?php
/**
 * ViewEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Thas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Thieme Meulenhoff Analytics Data API
 *
 * First setup of an API to exchange Learning Analytics. This API is based on events (inspired by Caliper Analytics® Specification, version 1.1) that are send to the api. We use a number of events.  The view event is used to register page views for theory.  The grade event is used to register results of doing assignments. Such a result is modelled as a score.  The assesment event is used to register the completion of an assignment. This information is transfered as an attempt.  Both theory and assignments are considered digital resources. An assignment is an assignable digital resource.  A student is seen as an actor.
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Thas;

use PHPUnit\Framework\TestCase;

/**
 * ViewEventTest Class Doc Comment
 *
 * @category    Class
 * @description ViewEvent
 * @package     Thas
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ViewEventTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ViewEvent"
     */
    public function testViewEvent()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "actor"
     */
    public function testPropertyActor()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "event_time"
     */
    public function testPropertyEventTime()
    {
    }

    /**
     * Test attribute "started_at_time"
     */
    public function testPropertyStartedAtTime()
    {
    }

    /**
     * Test attribute "ended_at_time"
     */
    public function testPropertyEndedAtTime()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }
}
